### ISSUE TITLE
Compose install fails

### ISSUE THREAD

**Issue by hamilton2030** [mrbobbytables/salty-docker#5]
```
      ID: get-compose
Function: cmd.run
    Name: curl -L https://github.com/docker/compose/releases/download/None/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
```

chmod +x /usr/local/bin/docker-compose

```
  Result: True
 Comment: Command "curl -L https://github.com/docker/compose/releases/download/None/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          " run
 Started: 19:58:55.629777
Duration: 1165.295 ms
 Changes:
          ----------
          pid:
              10922
          retcode:
              0
          stderr:
                % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                               Dload  Upload   Total   Spent    Left  Speed

                0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
                0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
              100    21    0    21    0     0     18      0 --:--:--  0:00:01 --:--:--    18
          stdout:
```

---

```
      ID: get-compose-completion
Function: cmd.wait
    Name: curl -L https://raw.githubusercontent.com/docker/compose/None/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose

  Result: True
 Comment: Command "curl -L https://raw.githubusercontent.com/docker/compose/None/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
          " run
 Started: 19:58:56.799389
Duration: 708.66 ms
 Changes:
          ----------
          pid:
              10929
          retcode:
              0
          stderr:
                % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                               Dload  Upload   Total   Spent    Left  Speed

                0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
                0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
              100    15  100    15    0     0     22      0 --:--:-- --:--:-- --:--:--    22
          stdout:
```
## Summary for webserver

[root@webserver compose]# cat /srv/pillars/docker.sls
docker:
  lookup:
    engine:
      version: 1.11.2
      env_vars:
        DOCKER_HOST: /var/run/docker.sock
        TLS_VERIFY: TRUE
      opts:
        dns:
          - 8.8.8.8
          - 8.8.4.4
# 

```
compose:
  version: 1.7.1
  completion: true
```

For some reason formula fails to pick up the version number.

Though command works manually:
[root@webserver compose]# curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    555      0 --:--:--  0:00:01 --:--:--   556
100 7776k  100 7776k    0     0   342k      0  0:00:22  0:00:22 --:--:--  545k

Any ideas would be appreciated.

**Comment by hamilton2030** [comment]
worked as a charm when I explicitly specify version:

get-compose:
  cmd.run:
    - name: |
        curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
    - unless: docker-compose --version | grep -q {{ compose.version }}
    - require:
      - pkg: get-compose-prereq-curl

{% if compose.completion %}
get-compose-completion:
  cmd.wait:
    - name: |
        curl -L https://raw.githubusercontent.com/docker/compose/1.7.1/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
    - watch:
      - cmd: get-compose
    - require:
      - pkg: get-compose-prereq-curl
{% endif %}

Had a look at mapping file - seem to be ok. 

Puzzled.

**Comment by mrbobbytables** [comment]
Yup, the specifying the compose version is required. If you take a peak at [defaults.yml](https://github.com/mrbobbytables/salt-docker-formula/blob/master/docker/defaults.yml), you can see the version in there is blank. You can get away with not specifying a version for the docker-engine as it'll just install the latest. However, for compose -- as it's not a package and is grabbed via curl, the version is required to form the correct url.

**Comment by hamilton2030** [comment]
Yeap and I specified that in pillar file:

[root@webserver compose]# cat /srv/pillars/docker.sls
docker:
  lookup:
    engine:
      version: 1.11.2
      env_vars:
        DOCKER_HOST: /var/run/docker.sock
        TLS_VERIFY: TRUE
      opts:
        dns:
          - 8.8.8.8
          - 8.8.4.4
#
    compose:
      version: 1.7.1
      completion: true

It did not work. So I had to specify it in a formula for installing compose:

[root@webserver compose]# cat /srv/formulas/salt-docker-formula/docker/compose/install.sls
{% from 'docker/map.jinja' import compose with context %}

get-compose-prereq-curl:
  pkg.installed:
    - name: curl

get-compose:
  cmd.run:
    - name: |
        curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
    - unless: docker-compose --version | grep -q {{ compose.version }}
    - require:
      - pkg: get-compose-prereq-curl

{% if compose.completion %}
get-compose-completion:
  cmd.wait:
    - name: |
        curl -L https://raw.githubusercontent.com/docker/compose/1.7.1/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
    - watch:
      - cmd: get-compose
    - require:
      - pkg: get-compose-prereq-curl
{% endif %}

which I assume is not the way t specify it. 

Bottomline  - a far as I understand you designed fromula to pick up version nukmber of compose from pillar file. And it did not work in my case. Do you think you can help me figure out why?

Thanks,
Leo

**Comment by hamilton2030** [comment]
Sorry for some reason it brakes the whole formatting.
Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/20318629/16617985/fc5c0a8c-43da-11e6-94ed-9d6bdde5a18e.png)

**Comment by mrbobbytables** [comment]
The formatting on the pillar looks okay from the screenshot, but hard to tell. If you use the markdown [codeblock](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code), it should preserve formatting when pasting in code/yaml etc.

I did a quick test of the compose component of the formula itself with salt version 2015.8.4 and 2016.3.1 with the defaults in the `pillar.example` as well as the following:

```
docker:
  lookup:
    compose:
      version: 1.7.1
      completion: true
```

and both worked successfully.

One thing with the `compose/install.sls` -- the version should not be manually put in there. It should use the jinja variable referencing the compose version (`{{ compose.version }}`).

**Comment by hamilton2030** [comment]
> One thing with the compose/install.sls -- the version should not be manually put in there. It should use the jinja variable referencing the compose version ({{ compose.version }}).

Exactly - but it was the only way to make it work for me.

Can you please test my attached file and tell if there is anything wrong with it?

[docker.zip](https://github.com/mrbobbytables/salt-docker-formula/files/349792/docker.zip)

**Comment by mrbobbytables** [comment]
It worked for me without issue. Tested with centos-7, ubuntu-14.04, and salt version 2016.3.1.

**Comment by hamilton2030** [comment]
Weird, would you care for a teamviewer session? may be you could see something I don't see?

**Comment by mrbobbytables** [comment]
I cannot currently. It'd have to wait till sometime after 7pm EST (GMT -5)

**Comment by hamilton2030** [comment]
Basically after 10 hours? That would be fine with me. If you get home and still in condition to help please drop me a message on linkedin. I'll advise you the session ID and pass :) 

If it all gets a bit annoying  - no worries I have a workaround by specifying the version number in install file. So just have a look at how you feel when you get home.

And great thank you for your time!

**Comment by mrbobbytables** [comment]
After 9 hours~, I'm going to go ahead and close the issue here as it does not appear to be an issue with the formula itself and we can continue on linkedin.
